env:
    browser: true
    es6: true
extends: 'eslint:recommended'
parser: babel-eslint
parserOptions:
    sourceType: module
    ecmaVersion: 8
rules:
    indent:
      - off
    no-cond-assign:
        - off
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
    semi:
        - error
        - never
