extends: 'eslint:recommended'
env:
  es2020: true
parserOptions:
  sourceType: module
rules:
  indent:
    - off
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - avoidEscape: true
  semi:
    - error
    - never
  no-cond-assign:
    - off
  quote-props:
    - error
    - always
overrides:
  - files: ['*.mjs']
    env:
      worker: true
      browser: true
  - files: ['*.js', '*.test.*']
    env:
      node: true
      mocha: true
    rules:
      quote-props:
        - off
